import {
  Code2,
  Brain,
  Palette,
  Megaphone,
  Sparkles,
  Share2,
  Search,
  Globe,
  Smartphone,
  Monitor,
  Camera,
  Video,
  PenTool,
  Bot,
  Cpu,
  ShoppingCart,
  BarChart3,
  Rocket,
  Briefcase,
  ShieldCheck,
} from "lucide-react";

export const serviceIcons = {
  code2: Code2,
  brain: Brain,
  palette: Palette,
  megaphone: Megaphone,
  sparkles: Sparkles,
  share2: Share2,
  search: Search,
  globe: Globe,
  smartphone: Smartphone,
  monitor: Monitor,
  camera: Camera,
  video: Video,
  pentool: PenTool,
  bot: Bot,
  cpu: Cpu,
  shoppingcart: ShoppingCart,
  barchart3: BarChart3,
  rocket: Rocket,
  briefcase: Briefcase,
  shieldcheck: ShieldCheck,
};

export const serviceIconOptions = [
  { key: "code2", label: "Code2" },
  { key: "brain", label: "Brain" },
  { key: "palette", label: "Palette" },
  { key: "megaphone", label: "Megaphone" },
  { key: "sparkles", label: "Sparkles" },
  { key: "share2", label: "Share2" },
  { key: "search", label: "Search" },
  { key: "globe", label: "Globe" },
  { key: "smartphone", label: "Smartphone" },
  { key: "monitor", label: "Monitor" },
  { key: "camera", label: "Camera" },
  { key: "video", label: "Video" },
  { key: "pentool", label: "PenTool" },
  { key: "bot", label: "Bot" },
  { key: "cpu", label: "Cpu" },
  { key: "shoppingcart", label: "ShoppingCart" },
  { key: "barchart3", label: "BarChart3" },
  { key: "rocket", label: "Rocket" },
  { key: "briefcase", label: "Briefcase" },
  { key: "shieldcheck", label: "ShieldCheck" },
];
