import {
  Code2,
  Brain,
  Palette,
  Megaphone,
  Sparkles,
  Share2,
  Search,
  Globe,
  Smartphone,
  Monitor,
  Camera,
  Video,
  PenTool,
  Bot,
  Cpu,
  ShoppingCart,
  BarChart3,
  Rocket,
  Briefcase,
  ShieldCheck,
} from "lucide-react";

export const serviceIcons = {
  code2: Code2,
  brain: Brain,
  palette: Palette,
  megaphone: Megaphone,
  sparkles: Sparkles,
  share2: Share2,
  search: Search,
  globe: Globe,
  smartphone: Smartphone,
  monitor: Monitor,
  camera: Camera,
  video: Video,
  pentool: PenTool,
  bot: Bot,
  cpu: Cpu,
  shoppingcart: ShoppingCart,
  barchart3: BarChart3,
  rocket: Rocket,
  briefcase: Briefcase,
  shieldcheck: ShieldCheck,
};

export const serviceIconOptions = [
  { key: "code2", label: "Code2" },
  { key: "brain", label: "Brain" },
  { key: "palette", label: "Palette" },
  { key: "megaphone", label: "Megaphone" },
  { key: "sparkles", label: "Sparkles" },
  { key: "share2", label: "Share2" },
  { key: "search", label: "Search" },
  { key: "globe", label: "Globe" },
  { key: "smartphone", label: "Smartphone" },
  { key: "monitor", label: "Monitor" },
  { key: "camera", label: "Camera" },
  { key: "video", label: "Video" },
  { key: "pentool", label: "PenTool" },
  { key: "bot", label: "Bot" },
  { key: "cpu", label: "Cpu" },
  { key: "shoppingcart", label: "ShoppingCart" },
  { key: "barchart3", label: "BarChart3" },
  { key: "rocket", label: "Rocket" },
  { key: "briefcase", label: "Briefcase" },
  { key: "shieldcheck", label: "ShieldCheck" },
];

export const servicesData = [
  {
    id: 1,
    name: "Programmation Web",
    description:
      "Création de sites web modernes, rapides et optimisés pour tous les appareils.",
    icon: "code2",
    price: 2500,
    createdAt: "2026-05-20",
    status: "active",
  },
  {
    id: 2,
    name: "Solutions AI",
    description:
      "Développement d'outils intelligents, automatisation et chatbots innovants.",
    icon: "brain",
    price: 6000,
    createdAt: "2026-05-22",
    status: "active",
  },
  {
    id: 3,
    name: "Identité Visuelle",
    description:
      "Création de logos, chartes graphiques et branding professionnel.",
    icon: "palette",
    price: 1500,
    createdAt: "2026-05-24",
    status: "inactive",
  },
  {
    id: 4,
    name: "ADS Marketing",
    description:
      "Gestion de campagnes Google Ads et Meta Ads performantes.",
    icon: "megaphone",
    price: 3500,
    createdAt: "2026-05-28",
    status: "active",
  },
  {
    id: 5,
    name: "Création AI",
    description:
      "Création de contenus visuels modernes avec intelligence artificielle.",
    icon: "sparkles",
    price: 4000,
    createdAt: "2026-05-30",
    status: "inactive",
  },
  {
    id: 6,
    name: "Social Media",
    description:
      "Gestion et développement de votre présence sur les réseaux sociaux.",
    icon: "share2",
    price: 2000,
    createdAt: "2026-06-01",
    status: "active",
  },
  {
    id: 7,
    name: "SEO",
    description:
      "Optimisation du référencement naturel pour améliorer votre visibilité.",
    icon: "search",
    price: 1800,
    createdAt: "2026-06-02",
    status: "inactive",
  },
];